name: Generate CycloneDX SBOM and upload to Dependency-Track

on:
  push:
    branches: [ sec-sbom-investigation ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies and deploy artifacts
      run: npm install

    - name: Generate CycloneDX SBOM and upload to Dependency-Track
      uses: CycloneDX/gh-node-module-generatebom@v1
      with:
        path: './'
        output: './test.app.bom.xml'